// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrasi butuh koneksi non-pooled: pakai DIRECT_URL (Session pooler / port 5432)
    // kalau ada, jatuh ke DATABASE_URL kalau tidak.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
